name: dompetku
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0' # Menggunakan rentang versi yang lebih aman

dependencies:
  flutter:
    sdk: flutter
  
#  cupertino_icons: ^1.0.8
#  loading_animation_widget: ^1.2.0
#  google_fonts: ^6.2.1
  # firebase_core: ^3.5.0
  # firebase_auth: ^5.3.0
  # cloud_firestore: ^5.4.0
  
  # 📊 Tambahan untuk grafik & kalender
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2
  go_router: ^0.0.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.tff
        - asset: assets/fonts/Urbanist-Thin.tff
          weight: 100
        - asset: assets/fonts/Urbanist-Light.tff
          weight: 300
        - asset: assets/fonts/Urbanist-Medium.tff
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.tff
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.tff
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.tff
          weight: 800
